export const LocationExport = [

    // Andaman & Nicobar Islands
    { city: 'Andamans', state: 'Andaman & Nicobar Islands' },

    // Andhra Pradesh
    { city: 'Adilabad', state: 'Andhra Pradesh' },
    { city: 'Anantapur', state: 'Andhra Pradesh' },
    { city: 'Chittoor', state: 'Andhra Pradesh' },
    { city: 'Cuddapah', state: 'Andhra Pradesh' },
    { city: 'East Godavari', state: 'Andhra Pradesh' },
    { city: 'Guntur', state: 'Andhra Pradesh' },
    { city: 'Hyderabad', state: 'Andhra Pradesh' },
    { city: 'Hyderabad and Rangareddi', state: 'Andhra Pradesh' },
    { city: 'Karimnagar', state: 'Andhra Pradesh' },
    { city: 'Khammam', state: 'Andhra Pradesh' },
    { city: 'Krishna', state: 'Andhra Pradesh' },
    { city: 'Kurnool', state: 'Andhra Pradesh' },
    { city: 'Mahbubnagar', state: 'Andhra Pradesh' },
    { city: 'Medak', state: 'Andhra Pradesh' },
    { city: 'Nalgonda', state: 'Andhra Pradesh' },
    { city: 'Nellore', state: 'Andhra Pradesh' },
    { city: 'Nizamabad', state: 'Andhra Pradesh' },
    { city: 'Prakasam', state: 'Andhra Pradesh' },
    { city: 'Rangareddi', state: 'Andhra Pradesh' },
    { city: 'Srikakulam', state: 'Andhra Pradesh' },
    { city: 'Visakhapatnam', state: 'Andhra Pradesh' },
    { city: 'Vizianagaram', state: 'Andhra Pradesh' },
    { city: 'Warangal', state: 'Andhra Pradesh' },
    { city: 'West Godavari', state: 'Andhra Pradesh' },

    //Arunachal Pradesh
    { city: 'Changlang', state: 'Arunachal Pradesh' },
    { city: 'Dibang Valley', state: 'Arunachal Pradesh' },
    { city: 'East Kameng', state: 'Arunachal Pradesh' },
    { city: 'East Siang', state: 'Arunachal Pradesh' },
    { city: 'Lohit', state: 'Arunachal Pradesh' },
    { city: 'Lower Subansiri', state: 'Arunachal Pradesh' },
    { city: 'Papum Pare', state: 'Arunachal Pradesh' },
    { city: 'Tawang', state: 'Arunachal Pradesh' },
    { city: 'Tirap', state: 'Arunachal Pradesh' },
    { city: 'Upper Subansiri', state: 'Arunachal Pradesh' },
    { city: 'West Kameng', state: 'Arunachal Pradesh' },
    { city: 'West Siang', state: 'Arunachal Pradesh' },

    //Assam
    { city: 'Barpeta', state: 'Assam' },
    { city: 'Bongaigaon', state: 'Assam' },
    { city: 'Cachar', state: 'Assam' },
    { city: 'Darrang', state: 'Assam' },
    { city: 'Dhemaji', state: 'Assam' },
    { city: 'Dhubri', state: 'Assam' },
    { city: 'Dibrugarh', state: 'Assam' },
    { city: 'Goalpara', state: 'Assam' },
    { city: 'Golaghat', state: 'Assam' },
    { city: 'Hailakandi', state: 'Assam' },
    { city: 'Jorhat', state: 'Assam' },
    { city: 'Kamrup', state: 'Assam' },
    { city: 'Karbi Anglong', state: 'Assam' },
    { city: 'Karimganj', state: 'Assam' },
    { city: 'Kokrajhar', state: 'Assam' },
    { city: 'Lakhimpur', state: 'Assam' },
    { city: 'Marigaon', state: 'Assam' },
    { city: 'Nagaon', state: 'Assam' },
    { city: 'Nalbari', state: 'Assam' },
    { city: 'North Cachar Hills', state: 'Assam' },
    { city: 'Sibsagar', state: 'Assam' },
    { city: 'Sonitpur', state: 'Assam' },
    { city: 'Tinsukia', state: 'Assam' },

    //Bihar
    { city: 'Araria', state: 'Bihar' },
    { city: 'Banka', state: 'Bihar' },
    { city: 'Begusarai', state: 'Bihar' },
    { city: 'Bhagalpur', state: 'Bihar' },
    { city: 'Bhojpur', state: 'Bihar' },
    { city: 'Buxar', state: 'Bihar' },
    { city: 'Darbhanga', state: 'Bihar' },
    { city: 'Gaya', state: 'Bihar' },
    { city: 'Gopalganj', state: 'Bihar' },
    { city: 'Jamui', state: 'Bihar' },
    { city: 'Jehanabad', state: 'Bihar' },
    { city: 'Kaimur (Bhabua)', state: 'Bihar' },
    { city: 'Katihar', state: 'Bihar' },
    { city: 'Khagaria', state: 'Bihar' },
    { city: 'Kishanganj', state: 'Bihar' },
    { city: 'Lakhisarai', state: 'Bihar' },
    { city: 'Madhepura', state: 'Bihar' },
    { city: 'Madhubani', state: 'Bihar' },
    { city: 'Munger', state: 'Bihar' },
    { city: 'Muzaffarpur', state: 'Bihar' },
    { city: 'Nalanda', state: 'Bihar' },
    { city: 'Nawada', state: 'Bihar' },
    { city: 'Pashchim Champaran', state: 'Bihar' },
    { city: 'Patna', state: 'Bihar' },
    { city: 'Purba Champaran', state: 'Bihar' },
    { city: 'Purnia', state: 'Bihar' },
    { city: 'Rohtas', state: 'Bihar' },
    { city: 'Saharsa', state: 'Bihar' },
    { city: 'Samastipur', state: 'Bihar' },
    { city: 'Saran', state: 'Bihar' },
    { city: 'Sheikhpura', state: 'Bihar' },
    { city: 'Sheohar', state: 'Bihar' },
    { city: 'Sitamarhi', state: 'Bihar' },
    { city: 'Siwan', state: 'Bihar' },
    { city: 'Supaul', state: 'Bihar' },
    { city: 'Vaishali', state: 'Bihar' },

    //Chhattisgarh
    { city: 'Bastar', state: 'Chhattisgarh' },
    { city: 'Bilaspur', state: 'Chhattisgarh' },
    { city: 'Dantewada', state: 'Chhattisgarh' },
    { city: 'Dhamtari', state: 'Chhattisgarh' },
    { city: 'Durg', state: 'Chhattisgarh' },
    { city: 'Janjgir-Champa', state: 'Chhattisgarh' },
    { city: 'Jashpur', state: 'Chhattisgarh' },
    { city: 'Kanker', state: 'Chhattisgarh' },
    { city: 'Kawardha', state: 'Chhattisgarh' },
    { city: 'Korba', state: 'Chhattisgarh' },
    { city: 'Koriya', state: 'Chhattisgarh' },
    { city: 'Mahasamund', state: 'Chhattisgarh' },
    { city: 'Raipur', state: 'Chhattisgarh' },
    { city: 'Rajnandgaon', state: 'Chhattisgarh' },
    { city: 'Surguja', state: 'Chhattisgarh' },
    { city: 'Dadra & Nagar Haveli', state: 'Dadra & Nagar Haveli' },
    { city: 'Daman', state: 'Daman & Diu' },
    { city: 'Diu', state: 'Daman & Diu' },
    { city: 'East', state: 'Delhi' },

    //New Delhi & Chandigarh
    { city: 'Chandigarh', state: 'Chandigarh' },
    { city: 'In all 9 dsitricts', state: 'Delhi' },
    { city: 'North', state: 'Delhi' },
    { city: 'North East', state: 'Delhi' },
    { city: 'North West', state: 'Delhi' },
    { city: 'South', state: 'Delhi' },
    { city: 'South West', state: 'Delhi' },
    { city: 'New Delhi', state: 'New Delhi' },

    //Goa
    { city: 'North Goa', state: 'Goa' },
    { city: 'South Goa', state: 'Goa' },

    //Gujrat
    { city: 'Ahmadabad', state: 'Gujarat' },
    { city: 'Amreli', state: 'Gujarat' },
    { city: 'Anand', state: 'Gujarat' },
    { city: 'Banas Kantha', state: 'Gujarat' },
    { city: 'Bharuch', state: 'Gujarat' },
    { city: 'Bhavnagar', state: 'Gujarat' },
    { city: 'Dohad', state: 'Gujarat' },
    { city: 'Gandhinagar', state: 'Gujarat' },
    { city: 'Jamnagar', state: 'Gujarat' },
    { city: 'Junagadh', state: 'Gujarat' },
    { city: 'Kachchh', state: 'Gujarat' },
    { city: 'Kheda', state: 'Gujarat' },
    { city: 'Mahesana', state: 'Gujarat' },
    { city: 'Narmada', state: 'Gujarat' },
    { city: 'Navsari', state: 'Gujarat' },
    { city: 'Panch Mahals', state: 'Gujarat' },
    { city: 'Patan', state: 'Gujarat' },
    { city: 'Porbandar', state: 'Gujarat' },
    { city: 'Rajkot', state: 'Gujarat' },
    { city: 'Sabar Kantha', state: 'Gujarat' },
    { city: 'Surat', state: 'Gujarat' },
    { city: 'Surendranagar', state: 'Gujarat' },
    { city: 'Vadodara', state: 'Gujarat' },
    { city: 'Valsad', state: 'Gujarat' },

    //Haryana 
    { city: 'Ambala', state: 'Haryana' },
    { city: 'Bhiwani', state: 'Haryana' },
    { city: 'Faridabad', state: 'Haryana' },
    { city: 'Fatehabad', state: 'Haryana' },
    { city: 'Gurgaon', state: 'Haryana' },
    { city: 'Hisar', state: 'Haryana' },
    { city: 'Jhajjar', state: 'Haryana' },
    { city: 'Jind', state: 'Haryana' },
    { city: 'Kaithal', state: 'Haryana' },
    { city: 'Karnal', state: 'Haryana' },
    { city: 'Kurukshetra', state: 'Haryana' },
    { city: 'Mahendragarh', state: 'Haryana' },
    { city: 'Panchkula', state: 'Haryana' },
    { city: 'Panipat', state: 'Haryana' },
    { city: 'Rewari', state: 'Haryana' },
    { city: 'Rohtak', state: 'Haryana' },
    { city: 'Sirsa', state: 'Haryana' },
    { city: 'Sonipat', state: 'Haryana' },
    { city: 'Yamunanagar', state: 'Haryana' },

    //Himachal Pradesh
    { city: 'Chamba', state: 'Himachal Pradesh' },
    { city: 'Hamirpur', state: 'Himachal Pradesh' },
    { city: 'Kangra', state: 'Himachal Pradesh' },
    { city: 'Kullu', state: 'Himachal Pradesh' },
    { city: 'Mandi', state: 'Himachal Pradesh' },
    { city: 'Shimla', state: 'Himachal Pradesh' },
    { city: 'Sirmaur', state: 'Himachal Pradesh' },
    { city: 'Solan', state: 'Himachal Pradesh' },
    { city: 'Una', state: 'Himachal Pradesh' },

    //Jammu & Kashmir
    { city: 'Anantnag', state: 'Jammu & Kashmir' },
    { city: 'Badgam', state: 'Jammu & Kashmir' },
    { city: 'Baramula', state: 'Jammu & Kashmir' },
    { city: 'Doda', state: 'Jammu & Kashmir' },
    { city: 'Jammu', state: 'Jammu & Kashmir' },
    { city: 'Kargil', state: 'Jammu & Kashmir' },
    { city: 'Kathua', state: 'Jammu & Kashmir' },
    { city: 'Kupwara', state: 'Jammu & Kashmir' },
    { city: 'Leh (Ladakh)', state: 'Jammu & Kashmir' },
    { city: 'Pulwama', state: 'Jammu & Kashmir' },
    { city: 'Punch', state: 'Jammu & Kashmir' },
    { city: 'Rajauri', state: 'Jammu & Kashmir' },
    { city: 'Srinagar', state: 'Jammu & Kashmir' },
    { city: 'Udhampur', state: 'Jammu & Kashmir' },

    //Jharkhand
    { city: 'Bokaro', state: 'Jharkhand' },
    { city: 'Chatra', state: 'Jharkhand' },
    { city: 'Deoghar', state: 'Jharkhand' },
    { city: 'Dhanbad', state: 'Jharkhand' },
    { city: 'Dumka', state: 'Jharkhand' },
    { city: 'Garhwa', state: 'Jharkhand' },
    { city: 'Giridih', state: 'Jharkhand' },
    { city: 'Godda', state: 'Jharkhand' },
    { city: 'Gumla', state: 'Jharkhand' },
    { city: 'Hazaribag', state: 'Jharkhand' },
    { city: 'Kodarma', state: 'Jharkhand' },
    { city: 'Lohardaga', state: 'Jharkhand' },
    { city: 'Pakaur', state: 'Jharkhand' },
    { city: 'Palamu', state: 'Jharkhand' },
    { city: 'Pashchimi Singhbhum', state: 'Jharkhand' },
    { city: 'Purbi Singhbhum', state: 'Jharkhand' },
    { city: 'Ranchi', state: 'Jharkhand' },
    { city: 'Sahibganj', state: 'Jharkhand' },

    //Karnataka
    { city: 'Bagalkot', state: 'Karnataka' },
    { city: 'Bangalore', state: 'Karnataka' },
    { city: 'Bangalore Rural', state: 'Karnataka' },
    { city: 'Belgaum', state: 'Karnataka' },
    { city: 'Bellary', state: 'Karnataka' },
    { city: 'Bidar', state: 'Karnataka' },
    { city: 'Bijapur', state: 'Karnataka' },
    { city: 'Chamarajanagar', state: 'Karnataka' },
    { city: 'Chikmagalur', state: 'Karnataka' },
    { city: 'Chitradurga', state: 'Karnataka' },
    { city: 'Dakshina Kannada', state: 'Karnataka' },
    { city: 'Davanagere', state: 'Karnataka' },
    { city: 'Dharwad', state: 'Karnataka' },
    { city: 'Gadag', state: 'Karnataka' },
    { city: 'Gulbarga', state: 'Karnataka' },
    { city: 'Hassan', state: 'Karnataka' },
    { city: 'Haveri', state: 'Karnataka' },
    { city: 'Kodagu', state: 'Karnataka' },
    { city: 'Kolar', state: 'Karnataka' },
    { city: 'Koppal', state: 'Karnataka' },
    { city: 'Mandya', state: 'Karnataka' },
    { city: 'Mysore', state: 'Karnataka' },
    { city: 'Raichur', state: 'Karnataka' },
    { city: 'Shimoga', state: 'Karnataka' },
    { city: 'Tumkur', state: 'Karnataka' },
    { city: 'Udupi', state: 'Karnataka' },
    { city: 'Uttara Kannada', state: 'Karnataka' },

    //Kerala
    { city: 'Alappuzha', state: 'Kerala' },
    { city: 'Ernakulam', state: 'Kerala' },
    { city: 'Idukki', state: 'Kerala' },
    { city: 'Kannur', state: 'Kerala' },
    { city: 'Kasaragod', state: 'Kerala' },
    { city: 'Kollam', state: 'Kerala' },
    { city: 'Kottayam', state: 'Kerala' },
    { city: 'Kozhikode', state: 'Kerala' },
    { city: 'Malappuram', state: 'Kerala' },
    { city: 'Palakkad', state: 'Kerala' },
    { city: 'Pathanamthitta', state: 'Kerala' },
    { city: 'Thiruvananthapuram', state: 'Kerala' },
    { city: 'Thrissur', state: 'Kerala' },
    { city: 'Wayanad', state: 'Kerala' },

    //Lakshadweep
    { city: 'Lakshadweep', state: 'Lakshadweep' },

    //Madhya Pradesh
    { city: 'Balaghat', state: 'Madhya Pradesh' },
    { city: 'Barwani', state: 'Madhya Pradesh' },
    { city: 'Betul', state: 'Madhya Pradesh' },
    { city: 'Bhind', state: 'Madhya Pradesh' },
    { city: 'Bhopal', state: 'Madhya Pradesh' },
    { city: 'Chhatarpur', state: 'Madhya Pradesh' },
    { city: 'Chhindwara', state: 'Madhya Pradesh' },
    { city: 'Damoh', state: 'Madhya Pradesh' },
    { city: 'Datia', state: 'Madhya Pradesh' },
    { city: 'Dewas', state: 'Madhya Pradesh' },
    { city: 'Dhar', state: 'Madhya Pradesh' },
    { city: 'Dindori', state: 'Madhya Pradesh' },
    { city: 'East Nimar', state: 'Madhya Pradesh' },
    { city: 'Guna', state: 'Madhya Pradesh' },
    { city: 'Gwalior', state: 'Madhya Pradesh' },
    { city: 'Harda', state: 'Madhya Pradesh' },
    { city: 'Hoshangabad', state: 'Madhya Pradesh' },
    { city: 'Indore', state: 'Madhya Pradesh' },
    { city: 'Jabalpur', state: 'Madhya Pradesh' },
    { city: 'Jhabua', state: 'Madhya Pradesh' },
    { city: 'Katni', state: 'Madhya Pradesh' },
    { city: 'Mandla', state: 'Madhya Pradesh' },
    { city: 'Mandsaur', state: 'Madhya Pradesh' },
    { city: 'Morena', state: 'Madhya Pradesh' },
    { city: 'Narsimhapur', state: 'Madhya Pradesh' },
    { city: 'Neemuch', state: 'Madhya Pradesh' },
    { city: 'Panna', state: 'Madhya Pradesh' },
    { city: 'Raisen', state: 'Madhya Pradesh' },
    { city: 'Rajgarh', state: 'Madhya Pradesh' },
    { city: 'Ratlam', state: 'Madhya Pradesh' },
    { city: 'Rewa', state: 'Madhya Pradesh' },
    { city: 'Sagar', state: 'Madhya Pradesh' },
    { city: 'Satna', state: 'Madhya Pradesh' },
    { city: 'Sehore', state: 'Madhya Pradesh' },
    { city: 'Seoni', state: 'Madhya Pradesh' },
    { city: 'Shahdol', state: 'Madhya Pradesh' },
    { city: 'Shajapur', state: 'Madhya Pradesh' },
    { city: 'Sheopur', state: 'Madhya Pradesh' },
    { city: 'Shivpuri', state: 'Madhya Pradesh' },
    { city: 'Sidhi', state: 'Madhya Pradesh' },
    { city: 'Tikamgarh', state: 'Madhya Pradesh' },
    { city: 'Ujjain', state: 'Madhya Pradesh' },
    { city: 'Umaria', state: 'Madhya Pradesh' },
    { city: 'Vidisha', state: 'Madhya Pradesh' },
    { city: 'West Nimar', state: 'Madhya Pradesh' },

    //Maharashtra
    { city: 'Ahmadnagar', state: 'Maharashtra' },
    { city: 'Akola', state: 'Maharashtra' },
    { city: 'Amravati', state: 'Maharashtra' },
    { city: 'Aurangabad', state: 'Maharashtra' },
    { city: 'Bhandara', state: 'Maharashtra' },
    { city: 'Bid', state: 'Maharashtra' },
    { city: 'Buldana', state: 'Maharashtra' },
    { city: 'Chandrapur', state: 'Maharashtra' },
    { city: 'Dhule', state: 'Maharashtra' },
    { city: 'Gadchiroli', state: 'Maharashtra' },
    { city: 'Gondiya', state: 'Maharashtra' },
    { city: 'Hingoli', state: 'Maharashtra' },
    { city: 'Jalgaon', state: 'Maharashtra' },
    { city: 'Jalna', state: 'Maharashtra' },
    { city: 'Kolhapur', state: 'Maharashtra' },
    { city: 'Latur', state: 'Maharashtra' },
    { city: 'Mumbai', state: 'Maharashtra' },
    { city: 'Navi Mumbai', state: 'Maharashtra' },
    { city: 'Nagpur', state: 'Maharashtra' },
    { city: 'Nanded', state: 'Maharashtra' },
    { city: 'Nandurbar', state: 'Maharashtra' },
    { city: 'Nashik', state: 'Maharashtra' },
    { city: 'Osmanabad', state: 'Maharashtra' },
    { city: 'Parbhani', state: 'Maharashtra' },
    { city: 'Pune', state: 'Maharashtra' },
    { city: 'Raigarh', state: 'Maharashtra' },
    { city: 'Ratnagiri', state: 'Maharashtra' },
    { city: 'Sangli', state: 'Maharashtra' },
    { city: 'Satara', state: 'Maharashtra' },
    { city: 'Sindhudurg', state: 'Maharashtra' },
    { city: 'Solapur', state: 'Maharashtra' },
    { city: 'Thane', state: 'Maharashtra' },
    { city: 'Wardha', state: 'Maharashtra' },
    { city: 'Washim', state: 'Maharashtra' },
    { city: 'Yavatmal', state: 'Maharashtra' },

    //Manipur
    { city: 'Bishnupur', state: 'Manipur' },
    { city: 'Bishnupur & Imphal West', state: 'Manipur' },
    { city: 'Chandel', state: 'Manipur' },
    { city: 'Imphal East', state: 'Manipur' },
    { city: 'Imphal West', state: 'Manipur' },
    { city: 'Imphal West & Imphal East', state: 'Manipur' },
    { city: 'Thoubal', state: 'Manipur' },
    { city: 'Thoubal & Imphal West', state: 'Manipur' },
    
    //Meghalaya
    { city: 'East Garo Hills', state: 'Meghalaya' },
    { city: 'East Khasi Hills', state: 'Meghalaya' },
    { city: 'Jaintia Hills', state: 'Meghalaya' },
    { city: 'Ri Bhoi', state: 'Meghalaya' },
    { city: 'South Garo Hills', state: 'Meghalaya' },
    { city: 'West Garo Hills', state: 'Meghalaya' },
    { city: 'West Khasi Hills', state: 'Meghalaya' },

    //Mizoram
    { city: 'Aizawl', state: 'Mizoram' },
    { city: 'Champhai', state: 'Mizoram' },
    { city: 'Kolasib', state: 'Mizoram' },
    { city: 'Lunglei', state: 'Mizoram' },
    { city: 'Mamit', state: 'Mizoram' },
    { city: 'Saiha', state: 'Mizoram' },
    { city: 'Serchhip', state: 'Mizoram' },

    //Nagaland
    { city: 'Dimapur', state: 'Nagaland' },
    { city: 'Kohima', state: 'Nagaland' },
    { city: 'Mokokchung', state: 'Nagaland' },
    { city: 'Mon', state: 'Nagaland' },
    { city: 'Phek', state: 'Nagaland' },
    { city: 'Tuensang', state: 'Nagaland' },
    { city: 'Wokha', state: 'Nagaland' },
    { city: 'Zunheboto', state: 'Nagaland' },

    //Orissa
    { city: 'Anugul', state: 'Orissa' },
    { city: 'Balangir', state: 'Orissa' },
    { city: 'Baleshwar', state: 'Orissa' },
    { city: 'Bargarh', state: 'Orissa' },
    { city: 'Baudh', state: 'Orissa' },
    { city: 'Bhadrak', state: 'Orissa' },
    { city: 'Cuttack', state: 'Orissa' },
    { city: 'Debagarh', state: 'Orissa' },
    { city: 'Dhenkanal', state: 'Orissa' },
    { city: 'Gajapati', state: 'Orissa' },
    { city: 'Ganjam', state: 'Orissa' },
    { city: 'Jagatsinghapur', state: 'Orissa' },
    { city: 'Jajapur', state: 'Orissa' },
    { city: 'Jharsuguda', state: 'Orissa' },
    { city: 'Kalahandi', state: 'Orissa' },
    { city: 'Kandhamal', state: 'Orissa' },
    { city: 'Kendrapara', state: 'Orissa' },
    { city: 'Kendujhar', state: 'Orissa' },
    { city: 'Khordha', state: 'Orissa' },
    { city: 'Koraput', state: 'Orissa' },
    { city: 'Malkangiri', state: 'Orissa' },
    { city: 'Mayurbhanj', state: 'Orissa' },
    { city: 'Nabarangapur', state: 'Orissa' },
    { city: 'Nayagarh', state: 'Orissa' },
    { city: 'Nuapada', state: 'Orissa' },
    { city: 'Puri', state: 'Orissa' },
    { city: 'Rayagada', state: 'Orissa' },
    { city: 'Sambalpur', state: 'Orissa' },
    { city: 'Sonapur', state: 'Orissa' },
    { city: 'Sundargarh', state: 'Orissa' },
    
    //Pondicherry
    { city: 'Karaikal', state: 'Pondicherry' },
    { city: 'Mahe', state: 'Pondicherry' },
    { city: 'Pondicherry', state: 'Pondicherry' },
    { city: 'Yanam', state: 'Pondicherry' },

    //Punjab
    { city: 'Amritsar', state: 'Punjab' },
    { city: 'Bathinda', state: 'Punjab' },
    { city: 'Faridkot', state: 'Punjab' },
    { city: 'Fatehgarh Sahib', state: 'Punjab' },
    { city: 'Firozpur', state: 'Punjab' },
    { city: 'Gurdaspur', state: 'Punjab' },
    { city: 'Hoshiarpur', state: 'Punjab' },
    { city: 'Jalandhar', state: 'Punjab' },
    { city: 'Kapurthala', state: 'Punjab' },
    { city: 'Ludhiana', state: 'Punjab' },
    { city: 'Mansa', state: 'Punjab' },
    { city: 'Moga', state: 'Punjab' },
    { city: 'Muktsar', state: 'Punjab' },
    { city: 'Nawanshahr', state: 'Punjab' },
    { city: 'Patiala', state: 'Punjab' },
    { city: 'Rupnagar', state: 'Punjab' },
    { city: 'Sangrur', state: 'Punjab' },

    //Rajasthan
    { city: 'Ajmer', state: 'Rajasthan' },
    { city: 'Alwar', state: 'Rajasthan' },
    { city: 'Banswara', state: 'Rajasthan' },
    { city: 'Baran', state: 'Rajasthan' },
    { city: 'Barmer', state: 'Rajasthan' },
    { city: 'Bharatpur', state: 'Rajasthan' },
    { city: 'Bhilwara', state: 'Rajasthan' },
    { city: 'Bikaner', state: 'Rajasthan' },
    { city: 'Bundi', state: 'Rajasthan' },
    { city: 'Chittaurgarh', state: 'Rajasthan' },
    { city: 'Churu', state: 'Rajasthan' },
    { city: 'Dausa', state: 'Rajasthan' },
    { city: 'Dhaulpur', state: 'Rajasthan' },
    { city: 'Dungarpur', state: 'Rajasthan' },
    { city: 'Ganganagar', state: 'Rajasthan' },
    { city: 'Hanumangarh', state: 'Rajasthan' },
    { city: 'Jaipur', state: 'Rajasthan' },
    { city: 'Jaisalmer', state: 'Rajasthan' },
    { city: 'Jalor', state: 'Rajasthan' },
    { city: 'Jhalawar', state: 'Rajasthan' },
    { city: 'Jhunjhunun', state: 'Rajasthan' },
    { city: 'Jodhpur', state: 'Rajasthan' },
    { city: 'Karauli', state: 'Rajasthan' },
    { city: 'Kota', state: 'Rajasthan' },
    { city: 'Nagaur', state: 'Rajasthan' },
    { city: 'Pali', state: 'Rajasthan' },
    { city: 'Rajsamand', state: 'Rajasthan' },
    { city: 'Sawai Madhopur', state: 'Rajasthan' },
    { city: 'Sikar', state: 'Rajasthan' },
    { city: 'Sirohi', state: 'Rajasthan' },
    { city: 'Tonk', state: 'Rajasthan' },
    { city: 'Udaipur', state: 'Rajasthan' },

    //Sikkim
    { city: 'West', state: 'Sikkim' },

    //Tamil Nadu
    { city: 'Ariyalur', state: 'Tamil Nadu' },
    { city: 'Chennai', state: 'Tamil Nadu' },
    { city: 'Coimbatore', state: 'Tamil Nadu' },
    { city: 'Cuddalore', state: 'Tamil Nadu' },
    { city: 'Dharmapuri', state: 'Tamil Nadu' },
    { city: 'Dindigul', state: 'Tamil Nadu' },
    { city: 'Erode', state: 'Tamil Nadu' },
    { city: 'Kancheepuram', state: 'Tamil Nadu' },
    { city: 'Kanniyakumari', state: 'Tamil Nadu' },
    { city: 'Kapur', state: 'Tamil Nadu' },
    { city: 'Madurai', state: 'Tamil Nadu' },
    { city: 'Nagapattinam', state: 'Tamil Nadu' },
    { city: 'Namakkal', state: 'Tamil Nadu' },
    { city: 'Perambalur', state: 'Tamil Nadu' },
    { city: 'Pudukkottai', state: 'Tamil Nadu' },
    { city: 'Ramanathapuram', state: 'Tamil Nadu' },
    { city: 'Salem', state: 'Tamil Nadu' },
    { city: 'Sivaganga', state: 'Tamil Nadu' },
    { city: 'Thanjavur', state: 'Tamil Nadu' },
    { city: 'The Nilgiris', state: 'Tamil Nadu' },
    { city: 'Theni', state: 'Tamil Nadu' },
    { city: 'Thiruvallur', state: 'Tamil Nadu' },
    { city: 'Thiruvarur', state: 'Tamil Nadu' },
    { city: 'Tiruchirappalli', state: 'Tamil Nadu' },
    { city: 'Tirunelveli', state: 'Tamil Nadu' },
    { city: 'Tiruvanamalai', state: 'Tamil Nadu' },
    { city: 'Toothukudi', state: 'Tamil Nadu' },
    { city: 'Vellore', state: 'Tamil Nadu' },
    { city: 'Viluppuram', state: 'Tamil Nadu' },
    { city: 'Virudhunagar', state: 'Tamil Nadu' },

    //Tripura
    { city: 'Dhalai', state: 'Tripura' },
    { city: 'North Tripura', state: 'Tripura' },
    { city: 'South Tripura', state: 'Tripura' },
    { city: 'West Tripura', state: 'Tripura' },

    //Uttar Pradesh
    { city: 'Agra', state: 'Uttar Pradesh' },
    { city: 'Aligarh', state: 'Uttar Pradesh' },
    { city: 'Allahabad', state: 'Uttar Pradesh' },
    { city: 'Ambedaker Nagar', state: 'Uttar Pradesh' },
    { city: 'Auraiya', state: 'Uttar Pradesh' },
    { city: 'Azamgarh', state: 'Uttar Pradesh' },
    { city: 'Baghpat', state: 'Uttar Pradesh' },
    { city: 'Bahraich', state: 'Uttar Pradesh' },
    { city: 'Ballia', state: 'Uttar Pradesh' },
    { city: 'Balrampur', state: 'Uttar Pradesh' },
    { city: 'Banda', state: 'Uttar Pradesh' },
    { city: 'Barabanki', state: 'Uttar Pradesh' },
    { city: 'Bareilly', state: 'Uttar Pradesh' },
    { city: 'Basti', state: 'Uttar Pradesh' },
    { city: 'Bijnor', state: 'Uttar Pradesh' },
    { city: 'Budaun', state: 'Uttar Pradesh' },
    { city: 'Bulandshahr', state: 'Uttar Pradesh' },
    { city: 'Chandauli', state: 'Uttar Pradesh' },
    { city: 'Chitrakoot', state: 'Uttar Pradesh' },
    { city: 'Deoria', state: 'Uttar Pradesh' },
    { city: 'Etah', state: 'Uttar Pradesh' },
    { city: 'Etawah', state: 'Uttar Pradesh' },
    { city: 'Faizabad', state: 'Uttar Pradesh' },
    { city: 'Farrukhabad', state: 'Uttar Pradesh' },
    { city: 'Fatehpur', state: 'Uttar Pradesh' },
    { city: 'Firozabad', state: 'Uttar Pradesh' },
    { city: 'Gautam Buddha Nagar', state: 'Uttar Pradesh' },
    { city: 'Ghaziabad', state: 'Uttar Pradesh' },
    { city: 'Ghazipur', state: 'Uttar Pradesh' },
    { city: 'Gonda', state: 'Uttar Pradesh' },
    { city: 'Gorakhpur', state: 'Uttar Pradesh' },
    { city: 'Hardoi', state: 'Uttar Pradesh' },
    { city: 'Hathras', state: 'Uttar Pradesh' },
    { city: 'Jalaun', state: 'Uttar Pradesh' },
    { city: 'Jaunpur', state: 'Uttar Pradesh' },
    { city: 'Jhansi', state: 'Uttar Pradesh' },
    { city: 'Jyotiba Phule Nagar', state: 'Uttar Pradesh' },
    { city: 'Kannauj', state: 'Uttar Pradesh' },
    { city: 'Kanpur Dehat', state: 'Uttar Pradesh' },
    { city: 'Kanpur Nagar', state: 'Uttar Pradesh' },
    { city: 'Kaushambi', state: 'Uttar Pradesh' },
    { city: 'Kheri', state: 'Uttar Pradesh' },
    { city: 'Kushinagar', state: 'Uttar Pradesh' },
    { city: 'Lalitpur', state: 'Uttar Pradesh' },
    { city: 'Lucknow', state: 'Uttar Pradesh' },
    { city: 'Maharajganj', state: 'Uttar Pradesh' },
    { city: 'Mahoba', state: 'Uttar Pradesh' },
    { city: 'Mainpuri', state: 'Uttar Pradesh' },
    { city: 'Mathura', state: 'Uttar Pradesh' },
    { city: 'Mau', state: 'Uttar Pradesh' },
    { city: 'Meerut', state: 'Uttar Pradesh' },
    { city: 'Mirzapur', state: 'Uttar Pradesh' },
    { city: 'Moradabad', state: 'Uttar Pradesh' },
    { city: 'Muzaffarnagar', state: 'Uttar Pradesh' },
    { city: 'Pilibhit', state: 'Uttar Pradesh' },
    { city: 'Pratapgarh', state: 'Uttar Pradesh' },
    { city: 'Rae Bareli', state: 'Uttar Pradesh' },
    { city: 'Rampur', state: 'Uttar Pradesh' },
    { city: 'Saharanpur', state: 'Uttar Pradesh' },
    { city: 'Sant Kabir Nagar', state: 'Uttar Pradesh' },
    { city: 'Sant Ravidas Nagar', state: 'Uttar Pradesh' },
    { city: 'Shahjahanpur', state: 'Uttar Pradesh' },
    { city: 'Shrawasti', state: 'Uttar Pradesh' },
    { city: 'Siddharthnagar', state: 'Uttar Pradesh' },
    { city: 'Sitapur', state: 'Uttar Pradesh' },
    { city: 'Sonbhadra', state: 'Uttar Pradesh' },
    { city: 'Sultanpur', state: 'Uttar Pradesh' },
    { city: 'Unnao', state: 'Uttar Pradesh' },
    { city: 'Varanasi', state: 'Uttar Pradesh' },

    //Uttarakhand
    { city: 'Almora', state: 'Uttarakhand' },
    { city: 'Bageshwar', state: 'Uttarakhand' },
    { city: 'Chamoli', state: 'Uttarakhand' },
    { city: 'Champawat', state: 'Uttarakhand' },
    { city: 'Dehradun', state: 'Uttarakhand' },
    { city: 'Garhwal', state: 'Uttarakhand' },
    { city: 'Hardwar', state: 'Uttarakhand' },
    { city: 'Nainital', state: 'Uttarakhand' },
    { city: 'Pithoragarh', state: 'Uttarakhand' },
    { city: 'Rudraprayag', state: 'Uttarakhand' },
    { city: 'Tehri Garhwal', state: 'Uttarakhand' },
    { city: 'Tehri Garhwal & Garhwal', state: 'Uttarakhand' },
    { city: 'Udham Singh Nagar', state: 'Uttarakhand' },
    { city: 'Uttarkashi', state: 'Uttarakhand' },

    //West Bengal
    { city: 'Bankura', state: 'West Bengal' },
    { city: 'Barddhaman', state: 'West Bengal' },
    { city: 'Birbhum', state: 'West Bengal' },
    { city: 'Dakshin Dinajpur', state: 'West Bengal' },
    { city: 'Darjiling', state: 'West Bengal' },
    { city: 'Darjiling and Jalpaiguri', state: 'West Bengal' },
    { city: 'Haora', state: 'West Bengal' },
    { city: 'Hugli', state: 'West Bengal' },
    { city: 'Jalpaiguri', state: 'West Bengal' },
    { city: 'Koch Bihar', state: 'West Bengal' },
    { city: 'Kolkata', state: 'West Bengal' },
    { city: 'Maldah', state: 'West Bengal' },
    { city: 'Medinipur', state: 'West Bengal' },
    { city: 'Murshidabad', state: 'West Bengal' },
    { city: 'Nadia', state: 'West Bengal' },
    { city: 'North Twentyfour Parganas', state: 'West Bengal' },
    { city: 'Puruliya', state: 'West Bengal' },
    { city: 'South Twentyfour Parganas', state: 'West Bengal' },
    { city: 'Uttar Dinajpur', state: 'West Bengal' },
];